// app/layout.tsx

import { type Metadata } from 'next'

import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from '@/providers/modal-provider';
import { ToastProvider } from '@/providers/toast.provider';
import { ThemeProvider } from '@/providers/theme-provider';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Comp Shop",
  description: "Generated by create next app",
};

import { AuthProvider } from '@/providers/auth-provider';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem 
          disableTransitionOnChange
        >
          <AuthProvider>
            <ToastProvider />
            <ModalProvider />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}